export const COMPANY = {
  name: 'BITEK SOLUTIONS LIMITED',
  shortName: 'Bitek Solutions',
  tagline: 'Where Innovation Meets Reliability',
  established: 2024,
  location: 'Avondale, Lusaka, Zambia',
  address: '12006 Simon Mwansa Kapwepwe Road',
  contact: 'Mr. Noddy Vlahakis',
  phone: '+260 977289299',
  email: 'debbiemiti1@gmail.com',
  hours: '08:00 – 17:00',
  mission: 'To provide dependable ICT infrastructure and renewable energy solutions that improve operational efficiency for businesses and homes.',
  vision: "To become one of Zambia's most trusted ICT and renewable energy service providers.",
};

export const IMAGES = {
  hero: '/hero.jpg',
  serverRoom: '/serverroom.jpg',
  solarPanels: '/solarpanels.jpg',
  cabling1: '/cabling1.jpg',
  cabling2: '/cabling2.jpg',
  cabling3: '/cabling3.jpg',
  cctv: '/cctv.jpg',
  inverter: '/inverter.jpg',
  executive: '/executive.jpg',
  wifi: '/wifi.jpg',
  officeBuilding: '/officebuilding.jpg',
  solarInstall1: '/solarinstall1.jpg',
  solarInstall2: '/solarinstall2.jpg',
};

export const ICT_SERVICES = [
  {
    id: 'structured-cabling',
    title: 'Structured Cabling',
    shortDesc: 'Enterprise-grade structured cabling systems for reliable data and voice communication.',
    fullDesc: 'We design and install Cat6/Cat6A structured cabling systems that form the backbone of your network infrastructure. Our installations meet international standards and are built for scalability.',
    image: IMAGES.cabling1,
    benefits: ['High-speed data transfer', 'Future-proof infrastructure', 'Clean cable management', 'Standards compliant'],
    icon: 'cable',
  },
  {
    id: 'network-design',
    title: 'Network Design & Implementation',
    shortDesc: 'Custom network architecture designed for performance, security, and growth.',
    fullDesc: 'From LAN/WAN design to VLAN segmentation and firewall configuration, we build networks that deliver consistent performance and robust security for your organization.',
    image: IMAGES.cabling2,
    benefits: ['Custom architecture', 'High availability', 'Security focused', 'Scalable design'],
    icon: 'network',
  },
  {
    id: 'server-solutions',
    title: 'Server Installation & Management',
    shortDesc: 'Professional server deployment, virtualization, and ongoing management.',
    fullDesc: 'We deploy and manage physical and virtual server environments including Windows Server, Linux, and hypervisor platforms. Our solutions ensure maximum uptime and data integrity.',
    image: IMAGES.serverRoom,
    benefits: ['99.9% uptime target', 'Data redundancy', 'Remote management', 'Backup solutions'],
    icon: 'server',
  },
  {
    id: 'cctv-security',
    title: 'CCTV & Security Systems',
    shortDesc: 'Comprehensive surveillance and access control for complete premises security.',
    fullDesc: 'We install IP-based CCTV systems with remote viewing capabilities, motion detection, and integration with access control systems for comprehensive security coverage.',
    image: IMAGES.cctv,
    benefits: ['Remote monitoring', 'HD/4K cameras', 'Night vision', 'Mobile access'],
    icon: 'camera',
  },
  {
    id: 'wifi-solutions',
    title: 'Enterprise WiFi Solutions',
    shortDesc: 'High-performance wireless networks for seamless connectivity across your premises.',
    fullDesc: 'We design and deploy enterprise-grade WiFi solutions with centralized management, guest portals, and seamless roaming for offices, hotels, schools, and public venues.',
    image: IMAGES.wifi,
    benefits: ['Seamless roaming', 'Guest portals', 'Central management', 'High density support'],
    icon: 'wifi',
  },
  {
    id: 'it-support',
    title: 'IT Support & Maintenance',
    shortDesc: 'Proactive IT support and maintenance to keep your systems running optimally.',
    fullDesc: 'Our managed IT support services include preventive maintenance, helpdesk support, system monitoring, and rapid response to minimize downtime and maximize productivity.',
    image: IMAGES.cabling3,
    benefits: ['24/7 monitoring', 'Rapid response', 'Preventive maintenance', 'Cost effective'],
    icon: 'headphones',
  },
  {
    id: 'access-control',
    title: 'Access Control Systems',
    shortDesc: 'Biometric and card-based access control for secure facility management.',
    fullDesc: 'We implement modern access control solutions including biometric readers, proximity cards, and integrated time-attendance systems for secure and efficient facility management.',
    image: IMAGES.cabling1,
    benefits: ['Biometric options', 'Audit trails', 'Time attendance', 'Integration ready'],
    icon: 'fingerprint',
  },
  {
    id: 'infrastructure-audits',
    title: 'Infrastructure Audits',
    shortDesc: 'Comprehensive assessment of your IT infrastructure with actionable recommendations.',
    fullDesc: 'Our infrastructure audits evaluate your current ICT environment, identify vulnerabilities, and provide a detailed roadmap for improvement aligned with your business objectives.',
    image: IMAGES.serverRoom,
    benefits: ['Gap analysis', 'Risk assessment', 'Roadmap planning', 'Cost optimization'],
    icon: 'clipboard',
  },
];

export const ENERGY_SERVICES = [
  {
    id: 'solar-commercial',
    title: 'Commercial Solar Systems',
    shortDesc: 'Large-scale solar installations for businesses seeking energy independence and cost reduction.',
    fullDesc: 'We design and install commercial solar PV systems tailored to your energy consumption patterns. Our solutions include grid-tied, off-grid, and hybrid configurations with monitoring systems.',
    image: IMAGES.solarPanels,
    benefits: ['Reduced energy costs', 'Energy independence', 'Low maintenance', 'ROI within 3-5 years'],
  },
  {
    id: 'solar-residential',
    title: 'Residential Solar Solutions',
    shortDesc: 'Home solar systems for reliable backup power and reduced electricity bills.',
    fullDesc: 'Our residential solar packages provide reliable backup power for homes, protecting against load shedding while reducing monthly electricity costs.',
    image: IMAGES.solarInstall1,
    benefits: ['Load shedding protection', 'Lower bills', 'Property value increase', 'Clean energy'],
  },
  {
    id: 'battery-backup',
    title: 'Battery Backup Systems',
    shortDesc: 'Advanced battery storage solutions for uninterrupted power supply.',
    fullDesc: 'We install lithium-ion and lead-acid battery backup systems that store solar energy for use during outages, ensuring your critical systems never go down.',
    image: IMAGES.inverter,
    benefits: ['Uninterrupted power', 'Smart management', 'Scalable capacity', 'Long lifespan'],
  },
  {
    id: 'solar-maintenance',
    title: 'Solar System Maintenance',
    shortDesc: 'Ongoing maintenance and monitoring to maximize your solar investment.',
    fullDesc: 'Our maintenance programs include regular panel cleaning, inverter checks, battery health monitoring, and performance optimization to ensure peak system efficiency.',
    image: IMAGES.solarInstall2,
    benefits: ['Peak performance', 'Extended lifespan', 'Fault detection', 'Performance reports'],
  },
];

export const INDUSTRIES = [
  { name: 'Corporate Offices', icon: 'building', desc: 'End-to-end ICT infrastructure and energy solutions for modern workplaces.' },
  { name: 'Schools & Universities', icon: 'graduation', desc: 'Connected learning environments with reliable power and network infrastructure.' },
  { name: 'Government Institutions', icon: 'landmark', desc: 'Secure, compliant infrastructure solutions for public sector organizations.' },
  { name: 'Healthcare Facilities', icon: 'heart-pulse', desc: 'Critical infrastructure ensuring uninterrupted operations for healthcare providers.' },
  { name: 'NGOs & International Orgs', icon: 'globe', desc: 'Reliable connectivity and power solutions for development organizations.' },
  { name: 'Retail & Hospitality', icon: 'store', desc: 'Seamless customer experiences powered by robust technology infrastructure.' },
  { name: 'Residential Properties', icon: 'home', desc: 'Smart home solutions and solar backup power for modern residences.' },
  { name: 'Manufacturing', icon: 'factory', desc: 'Industrial-grade power and connectivity for manufacturing operations.' },
];

export const TESTIMONIALS = [
  {
    name: 'David Mwanza',
    role: 'IT Director',
    company: 'Lusaka Business Park',
    text: 'Bitek Solutions transformed our entire network infrastructure. The structured cabling installation was completed on time and the performance improvement was immediate. Their team is professional and technically excellent.',
    rating: 5,
  },
  {
    name: 'Grace Tembo',
    role: 'Operations Manager',
    company: 'Greenfield Academy',
    text: 'The solar installation has reduced our electricity costs by over 40%. Bitek Solutions handled everything from design to commissioning. We now have reliable power even during load shedding.',
    rating: 5,
  },
  {
    name: 'Michael Banda',
    role: 'CEO',
    company: 'Zambezi Trading Co.',
    text: 'We chose Bitek Solutions for our CCTV and access control system. The quality of equipment and installation exceeded our expectations. Their ongoing support has been outstanding.',
    rating: 5,
  },
  {
    name: 'Sarah Phiri',
    role: 'Facility Manager',
    company: 'Avondale Medical Centre',
    text: 'As a healthcare facility, we cannot afford downtime. Bitek Solutions designed a hybrid solar system with battery backup that keeps our critical systems running 24/7. Exceptional service.',
    rating: 5,
  },
];

export const PROJECTS = [
  {
    title: 'Lusaka Business Park Network Overhaul',
    category: 'ICT Infrastructure',
    description: 'Complete network redesign and structured cabling installation for a 5-building business park serving 200+ tenants.',
    image: IMAGES.cabling2,
    scope: ['Structured cabling (Cat6A)', 'Core network switches', 'Fiber backbone', 'WiFi deployment'],
    result: '99.9% network uptime achieved',
  },
  {
    title: 'Greenfield Academy Solar Installation',
    category: 'Renewable Energy',
    description: '50kW solar PV system with battery backup for a private school campus, eliminating load shedding disruptions.',
    image: IMAGES.solarPanels,
    scope: ['50kW solar array', '100kWh battery storage', 'Hybrid inverter system', 'Monitoring platform'],
    result: '42% reduction in energy costs',
  },
  {
    title: 'Avondale Medical Centre Security System',
    category: 'Security Systems',
    description: 'Comprehensive CCTV and access control system covering all entry points and critical areas of the medical facility.',
    image: IMAGES.cctv,
    scope: ['32 IP cameras', 'Biometric access control', 'Central monitoring station', 'Mobile app access'],
    result: 'Full premises coverage with remote monitoring',
  },
  {
    title: 'Zambezi Trading Headquarters',
    category: 'ICT Infrastructure',
    description: 'Server room build-out with virtualization, backup systems, and enterprise WiFi for a growing trading company.',
    image: IMAGES.serverRoom,
    scope: ['Server room construction', 'VMware deployment', 'Backup solution', 'Enterprise WiFi'],
    result: 'Zero unplanned downtime since deployment',
  },
  {
    title: 'Residential Solar Estate Project',
    category: 'Renewable Energy',
    description: 'Solar installations for 15 residential properties in a new estate development, each with 10kW systems.',
    image: IMAGES.solarInstall1,
    scope: ['15 x 10kW systems', 'Battery backup per unit', 'Smart monitoring', 'Grid-tie capability'],
    result: 'Average 60% reduction in electricity bills',
  },
  {
    title: 'Government Office Complex Upgrade',
    category: 'ICT Infrastructure',
    description: 'Network infrastructure modernization for a government office complex serving 500+ staff members.',
    image: IMAGES.cabling3,
    scope: ['Network redesign', 'Fiber optic backbone', 'VoIP deployment', 'Security systems'],
    result: 'Modernized infrastructure supporting digital transformation',
  },
];

export const STATS = [
  { value: 150, suffix: '+', label: 'Projects Completed' },
  { value: 99.9, suffix: '%', label: 'Uptime Guarantee' },
  { value: 500, suffix: '+', label: 'Clients Served' },
  { value: 24, suffix: '/7', label: 'Technical Support' },
];

export const VALUES = [
  { title: 'Reliability', desc: 'We build infrastructure that works consistently, day after day.' },
  { title: 'Excellence', desc: 'Every installation meets the highest professional standards.' },
  { title: 'Partnership', desc: 'We invest in long-term relationships with our clients.' },
  { title: 'Innovation', desc: 'We leverage the latest technology to deliver optimal solutions.' },
  { title: 'Integrity', desc: 'Transparent pricing, honest advice, and ethical business practices.' },
  { title: 'Local Expertise', desc: 'Deep understanding of Zambian infrastructure challenges.' },
];
